feat: add banner component
the-guild-org/the-guild-components pull request #283
Opened 2021-12-13 03:47 UTC by saihaj

closes #280﻿

Reviewers: @PabloSzx @B2o5T

2021-12-13 09:09 UTC, dotansimha approved these changes

2021-12-13 10:04 UTC, B2o5T commented
@saihaj I think the main feature of the banner component in `graphql-config` it's his `background` with a `linear gradient` and with `animation`, do you think we need to add that styles by default? And the possibility to change them via `props`?

Also I think that text must by centered by default, and default padding must be 15px 25ps instead 8px 8px.

Maybe also add possibility to close the banner? need to take a look at existing banners how this was implemented.

2021-12-13 16:04 UTC, PabloSzx requested changes
Banner is not being re-exported from the `src/index.tsx` and the project only ships a bundled version of `src/index.tsx`

2021-12-21 04:59 UTC, saihaj commented
>  need to take a look at existing banners how this was implemented.

The current banner just sticks to the page there is no way to hide it.

2021-12-21 05:01 UTC, saihaj commented
Not sure why the build is failing now :/

2022-01-23 05:09 UTC, saihaj commented
@B2o5T @PabloSzx any idea why this is failing?

2022-02-07 15:19 UTC, B2o5T commented on packages/components/src/components/Banner.styles.ts
> +      background-size: 400% 200%;
you forget to specify this style, so there was no animation

2022-02-07 15:23 UTC, merged